### ISSUE TITLE
Button/command to display priority order per class

### ISSUE THREAD

**Issue by ruscur** [Alumian/CEPGP#13]
The !info command shows someone's current EPGP, but it's not all that useful without the context of the rest of the raid.  I think it would be cool to have a command that displayed what a player's current priority ranking is compared to others of their class in a raid, to give them an idea of how likely they are to win something off the next boss.

Could also be a loot master triggered thing that displays in raid chat.

**Comment by Alumian** [comment]
Hi Ruscur,
Thanks for the suggestion. Doesn't sound difficult to implement. What I'll do is I'll add a command for each, I'd rather avoid implementing a button if that's okay. I'll add a setting in the options menu to post in addition to !need messages. How does that sound?

**Comment by Alumian** [comment]
I have added the requested functionality. To avoid threat of disconnection or spam/flood protection measures, I have made use of the addon comms channel.
Essentially this means that if a player would like their EPGP report, they **must** have the addon enabled.
Please let me know if you find any bugs with this new functionality. I have not had a chance to test it extensively.

**Comment by ruscur** [comment]
great stuff, thanks

**Comment by ruscur** [comment]
I think it'd be nice to be able to do this over whispers so people don't need the addon installed, which has its own baggage (like not being able to hide offline guild members).  Maybe there could be an option (off by default) to go over whispers instead?  In my case I'm pretty confident I wouldn't get disconnected or anything.

I might work on that myself and send a PR.

**Comment by Alumian** [comment]
I'll put an option to whisper or not, but the only reason is if you send out too many whispers in a short time frame then you may get muted depending on what server you're playing on. So I'll put in the option, but I'll set it to addon message by default because I really don't want people getting muted because of this addon.

Also, in regards to not being able to hide offline guild members, I've looked into it and due to the limited functionality of the 1.12.1 API, addons are only able to read guild members that you can see. Meaning, if you hide offline guild members, the addon will not be able to see them. I will do some more research and experiment a little bit to see if I can allow that functionality without compromising the addon.

Could you please open a new issue with these details so I don't forget about it?

Thanks,
Alumian.
