### ISSUE TITLE
will u keep it update for wow classic?

### ISSUE THREAD

**Issue by chikoba** [Alumian/CEPGP#29]
hello mate!

we will use epgp for blizzard wow classic.

will u keep the addon up to date?

i hope i can read from you on:

https://willitclassic.com/

or maybe u will keep the work from the core epgp team at

https://groups.google.com/forum/#!forum/epgp-discuss

greetz my friend,
keep azeroth safe

**Comment by Alumian** [comment]
Hi Chikoba,

Thanks for your question. The short answer is, I'm not sure honestly. I'm currently working on re-writing CEPGP, it shouldn't take too much longer. The reason why I'm not sure is, at this point I'm not planning on playing Classic WOW and it has been announced that there will be changes to the API.
Depending on how many changes affect CEPGP, that will determine whether or not I continue updating the addon. At this stage, I'm expecting that minor modifications will need to be made to make it compatible, but nothing too drastic.
I'm planning on releasing the new version which users of BCEPGP will be familiar with and that will be the version that I intend to release in Classic WOW.

I hope that answers your question.

**Comment by Alumian** [comment]
Hi Chikoba,
I just wanted to let you know that I have just launched a major update for this addon to the version that I plan to release for Classic WoW. You can check it out here: https://github.com/Alumian/CEPGP/tree/beta if you're interested. Just letting you know though, this is still in beta and errors or abnormal behaviour may occur since I haven't had a chance to test it extensively. Regardless, it does have significantly more functionality than the original release. If you do choose to try the beta version, I do recommend you backup your saved variables file located at World of Warcraft\WTF\Account\<AccountName>\SavedVariables\CEPGP.lua.
I have also made posts on those forums that you have recommended - thanks for that! If you have any other questions or comments, please feel free to open a new ticket.

Thanks,
Alumian
