### ISSUE TITLE
List of Loot and GP Values

### ISSUE THREAD

**Issue by TheGreekOne** [Alumian/CEPGP#31]
Alumian,

Thank you for working on this awesome addon for the community!  

We are a guild preparing for Classic launch and are working on planning out our EP/GP system and the respective values.  I was hoping you could point me in the right direction for finding some kind of list that has the GP value of the loot that will be available.

Is there a standalone tool for calculating GP?  I would like to be able to play around with the various modifiers and see what impact that has on the GP values... but currently the only way I can see how much each piece of loot is worth is when it actually drops in a raid.  Let me know if you have any thoughts, thanks!

**Comment by Alumian** [comment]
Hey TheGreekOne,

Thanks for the great question! Unfortunately I'm not too sure that I can help you on this one I'm sorry. I don't know of any list of GP values for items, mostly because the GP formula is dynamic and changes from person to person depending on their own preferences.
If you could find a list that contains the item level, rarity and slot of each item then you could put that into an excel spreadsheet with the formula, but at this stage I'm not aware of such a resource.

I hope that helps!

**Comment by TheGreekOne** [comment]
No worries I will put together a spreadsheet, thanks for the suggestion!
