### ISSUE TITLE
Addon not supporting  guilds over 300 players

### ISSUE THREAD

**Issue by Cigarzz** [Alumian/CEPGP#7]
Hi on my server guild caps are at 642 the addon works in other guilds but does not support larger guild numbers i was able to change

[7] = math.floor((EP/GP)*100)/100,
 to 
[7] = math.floor((EP/(GP or 0))*100)/100,

just wondering if you could provide me with a floorless .lua

**Comment by Alumian** [comment]
Hi Cigarzz,
Sorry for not getting back to you sooner - are you still having the issue?
Math.floor simply rounds a number down to a whole number, in this case, it is calculating the player's PR and rounding it down, changing it to a percentage and then dividing by 100 to make it friendlier to read. So this shouldn't be affected by the size of your guild.

When you have this issue, do you have show offline members checked? Due to the limited API in classic WoW, the functions provided to me can only read the guild members that you can see.

Thanks,
Alumian.
